/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Laboratorio-Info
 */
public class Inicio_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Inicio_GUI
     */
    public Inicio_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PAINEL = new javax.swing.JPanel();
        atestado_BTN = new javax.swing.JButton();
        declaração_BNT = new javax.swing.JButton();
        comparecimento_BTN = new javax.swing.JButton();
        sair_BTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setUndecorated(true);

        PAINEL.setLayout(null);

        atestado_BTN.setText("ATESTADO");
        atestado_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atestado_BTNActionPerformed(evt);
            }
        });
        PAINEL.add(atestado_BTN);
        atestado_BTN.setBounds(100, 40, 180, 23);

        declaração_BNT.setText("DECLARAÇÃO");
        declaração_BNT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                declaração_BNTActionPerformed(evt);
            }
        });
        PAINEL.add(declaração_BNT);
        declaração_BNT.setBounds(102, 149, 180, 23);

        comparecimento_BTN.setText("COMPARECIMENTO");
        comparecimento_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comparecimento_BTNActionPerformed(evt);
            }
        });
        PAINEL.add(comparecimento_BTN);
        comparecimento_BTN.setBounds(101, 255, 190, 23);

        sair_BTN.setText("X");
        sair_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sair_BTNActionPerformed(evt);
            }
        });
        PAINEL.add(sair_BTN);
        sair_BTN.setBounds(323, 0, 80, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PAINEL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PAINEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(400, 308));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void atestado_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atestado_BTNActionPerformed
        try {
            Controller.atestado_DAO.Impressão();
        } catch (Exception ex) {
            Logger.getLogger(Inicio_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_atestado_BTNActionPerformed

    private void declaração_BNTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_declaração_BNTActionPerformed
        try {
            Controller.declaração_DAO.Impressão2();
        } catch (Exception ex) {
            Logger.getLogger(Inicio_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_declaração_BNTActionPerformed

    private void comparecimento_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comparecimento_BTNActionPerformed
        try {
            Controller.comparecimento_DAO.Impressão3();
        } catch (Exception ex) {
            Logger.getLogger(Inicio_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_comparecimento_BTNActionPerformed

    private void sair_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sair_BTNActionPerformed
    System.exit(0);
    }//GEN-LAST:event_sair_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PAINEL;
    private javax.swing.JButton atestado_BTN;
    private javax.swing.JButton comparecimento_BTN;
    private javax.swing.JButton declaração_BNT;
    private javax.swing.JButton sair_BTN;
    // End of variables declaration//GEN-END:variables
}
